line-length = 110
exclude = ["**/ecetin/**", "**/__pycache__/**", "**/slurm_logs/**", "**/outputs/**", "**/profiling_results/**", "**/logs/**"]

[lint]
select = ["C", "E", "F", "W"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]    # Ignore import unused violation
