model_path: "./assets/models/blender-net-8"
blender_exe_path: "/Applications/Blender.app/Contents/MacOS/Blender"

# Memory optimization settings
quantization: "8bit" # Options: null, "4bit", "8bit"
max_memory_gb: 8.0 # Maximum memory to use (adjust based on your system)
max_tokens: 1024

prompt: null
obj_name: null
brightness: null

verbose: false

output_path: "./assets/outputs/"
